### ISSUE TITLE
Request for arrow key support to select a profile and enter key to launch a profile

### ISSUE THREAD

**Issue by lolwut405** [yannrouillard/aws-sso-profiles-switcher#11]
Would it be possible to add support for selecting a profile with the up/down arrow keys and then launching the selected profile with the enter key?

I use the Firefox extension keyboard shortcut to open the profile selector popup, start typing for the profile, and then have to move my mouse to select the profile.  I don't want to use my mouse for this.  Thank you.

**Comment by yannrouillard** [comment]
Hi @lolwut405 

Sorry for the delay to answer.
I understand the need, I will have a look at it.
There is some UI question about how to show the currently selected one if both the mouse and the keyboard can select it
(the mouse automatically highlights the entry below its pointer, if someone types up/down, then the keyboard and the mouse are in disagreement about which one is selected).

Meanwhile, be aware that you can enter several search terms in the search bar to refine the search so the only one remaining is the one you want.
