### ISSUE TITLE
Latest AWS Console update for IAM Identity Centre Portal has broken the plugin integration

### ISSUE THREAD

**Issue by bryan-srg** [yannrouillard/aws-sso-profiles-switcher#12]
I'm sure you'll discover this yourself soon enough, but I've had a new update to the IAM IC portal page pushed to me, and the extension no longer parses it properly - so all my SSO profiles have no disappeared from the extension and I can't use it to switch roles any more.

**Comment by yannrouillard** [comment]
Hi @bryan-srg,

Thanks for the info, indeed the new AWS Access Portal is widely pushed now and its new layout broke the parsing logic.
I just pushed a new version of the extension (`0.4.3`) which should fix the issue (and support both the new and the old layout in case).

I successfully tested it in my side, can you test it and confirm it works fine on your side as well?

**Comment by bryan-srg** [comment]
Hi @yannrouillard - just tested the new version - working perfectly - thanks so much for the speedy turnaround!

**Comment by n1rna** [comment]
<3 Thanks for the rather quick fix :)
